name: 'Validate Dependabot Configuration'
description:
  'Validate that dependabot.yml is configured for all supported languages that
  are present in the repository.'
author: 'chrisreddington'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'package'
  color: 'blue'

inputs:
  github-token:
    description: >
      Personal access token (PAT) used to query the languages used in the
      repository.
    default: ${{ github.token }}

runs:
  using: node24
  main: dist/index.js
